spring.application.name=demoUltraMsg
server.servlet.context-path= /UltraMsg-msj
server.port=8080

ultramsg.instance1.id=instance109385
ultramsg.instance1.token=6s3u9jm7tt71i2e4
ultramsg.instance2.id=instance109487
ultramsg.instance2.token=rne3v2cxu3cz5vxe